project_id = "yjytuglxpvdkyvjsdyfk"

[functions.aggregate-weekly-earnings]
verify_jwt = false

[functions.process-payouts]
verify_jwt = false

[functions.approve-artist]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-subscription-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-connect-account]
verify_jwt = false

[functions.verify-connect-status]
verify_jwt = false

[functions.create-test-artist]
verify_jwt = false

[functions.upload-avatar]
verify_jwt = false

[functions.reset-test-password]
verify_jwt = false