name = "hls-queue-consumer"
main = "worker.js"
compatibility_date = "2026-02-22"
compatibility_flags = ["nodejs_compat"]
account_id = "2f10df893433e4290bf1e708621baae5"

[[queues.consumers]]
queue = "hls-transcode-queue"
max_batch_size = 1
max_batch_timeout = 30

[vars]
HLS_TRANSCODER_URL = "https://hls-transcoder-production-a5a3.up.railway.app/transcode"
HLS_TRANSCODER_TOKEN = "fbac6953058c22a7a9dfb06f99bf27db68a86f557582cb70ba1ce55b53e90d98"
HLS_TRANSCODER_TIMEOUT_MS = "120000"
